FROM php:7.3-fpm-alpine3.8

RUN apk add --update \
		postgresql-dev \
		zlib-dev \
		libzip-dev \
	&& docker-php-ext-install \
		pgsql \
		zip \
	&& apk del \
		postgresql-libs \
		libsasl \
		db \
		libzip \
		zlib \
		zip

ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_HOME /composer

COPY --from=composer /usr/bin/composer /usr/bin/composer