version: '3'
services:
    nginx:
        image: nginx:1.15-alpine
        ports:
            - 80:80
            - 443:443
        links:
            - php
        volumes:
            - ./apps:/var/www/

            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf

            - ./docker/nginx/sites-available:/etc/nginx/sites-available
            - ./docker/nginx/sites-available:/etc/nginx/sites-enabled

    php:
        image: php:7.3-fpm-alpine3.8
        volumes:
            - ./apps:/var/www/

