version: '3'
services:
    nginx:
        image: nginx:1.15-alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./apps:/var/www/
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf