version: '3'
services:
    composer:
        image: composer:1.8.0
        links:
            - php
    database:
        image: postgres:11.1-alpine
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: changeme
            POSTGRES_DB: db
        volumes:
            - database-volume:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - database
    nginx:
        image: nginx:1.15-alpine
        ports:
            - 80:80
            - 443:443
        links:
            - php
        volumes:
            - ./apps:/var/www/

            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf

            - ./docker/nginx/sites-available:/etc/nginx/sites-available
            - ./docker/nginx/sites-available:/etc/nginx/sites-enabled

            - ./docker/nginx/certs/development:/etc/ssl/ssl-certificates
    php:
        build: ./docker/php/
        volumes:
            - ./apps:/var/www/
        links:
            - database

volumes:
    database-volume:
        external: true
        


